analysis:
  flag: false
  load_graph: false
  load_graph_path: results/graph/gen
  project: gsl
  save_graph: false
dataset:
  EIGEN_VEC_NUM: 4
  add_loop: true
  cora_split: false
  feat_norm: false
  k: 5
  normalize: true
  sparse: true
  without_structure: knn
model:
  act: relu
  ci_dropout: 0.4788784961858262
  ci_nhid: 480
  gnn_dropout: 0.37985987731851656
  gnn_nhid: 352
  graph_learn_num_pers: 4
  hops: 2
  mlp_dropout: 0.48508771873605605
  mlp_layers: 6
  mlp_nhid: 416
  ratio_of_edge_insert: 0.2
  spmm_type: 0
training:
  criterion: metric
  data_cpu: false
  dta: 1.1
  eta: 0.3
  lr: 0.1
  max_epochs: 10000
  patience: 16
  weight_decay: 0.0005
